DROP TABLE IF EXISTS STOCK_SYMBOL PURGE;
CREATE TABLE IF NOT EXISTS STOCK_SYMBOL (
  SYMBOL STRING,
  COMPANY STRING,

  PRIMARY KEY (SYMBOL) DISABLE NOVALIDATE
);
INSERT OVERWRITE TABLE STOCK_SYMBOL VALUES ('CRM','SalesForce.com');
SELECT * FROM STOCK_SYMBOL;
