SELECT DOMAIN, AVG(CORE) Average_CPU_Usage, AVG(DB) Average_DB_Usage 
FROM WIDE_TABLE 
GROUP BY DOMAIN 
ORDER BY DOMAIN DESC;

-- Sum, Min and Max CPU usage by Salesforce grouped by day
SELECT TRUNC(DATE,'DAY') DAY, SUM(CORE) TOTAL_CPU_Usage, MIN(CORE) MIN_CPU_Usage, MAX(CORE) MAX_CPU_Usage,
  MIN(FILLER.INT2404) RANDOM_INT_MIN, MAX(FILLER.INT2404) RANDOM_INT_MAX, MIN(FILLER.FLOAT0804) RANDOM_FLOAT_MIN, MAX(FILLER.FLOAT0804) RANDOM_FLOAT_MAX
FROM WIDE_TABLE 
WHERE DOMAIN LIKE 'Salesforce%' 
GROUP BY TRUNC(DATE,'DAY');

-- list host and total active users when core CPU usage is 10X greater than DB usage
SELECT HOST, SUM(ACTIVE_VISITOR) TOTAL_ACTIVE_VISITORS, SUM(FILLER.INT1404) RANDOM_INT_SUM, SUM(FILLER.FLOAT2804) RANDOM_FLOAT_SUM
FROM WIDE_TABLE 
WHERE DB > (CORE * 10) 
GROUP BY HOST;
